# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.15.6-buster
        environment:
          ENV: CI
          GO111MODULE: "on"
    steps:
      - checkout
#      - run:
#          name: check tidy
#          command: |
#            go mod tidy
#            if ! git --no-pager diff --exit-code -- go.mod go.sum; then
#              echo modules are not tidy, please run 'go mod tidy'
#              exit 1
#            fi
      - run: go get -v -t -d ./...
      - run: go vet ./...
      - run: go get honnef.co/go/tools/cmd/staticcheck  && staticcheck --checks="all" --tags e2e ./...
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
            mkdir -p /tmp/test-results
      - run:
          command: |
            gotestsum --junitfile /tmp/test-results/unit-tests.xml -- -race -coverprofile=coverage.txt -covermode=atomic ./...
            bash <(curl -s https://codecov.io/bash)
            go tool cover -html=coverage.txt -o /tmp/artifacts/coverage.html
      - store_artifacts:
          path: /tmp/artifacts
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results