# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
commands:
  influxdb-onboarding:
    steps:
    - run:
        name: "Post onBoarding request to InfluxDB 2"
        command: ./scripts/influxdb-onboarding.sh
jobs:
  build:
    docker:
      # specify the version
      - image: cimg/go:1.17.2
        environment:
          ENV: CI
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go vet ./...
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck --checks="all" ./...
  tests:
    docker:
      - image: cimg/go:1.17.2
        environment:
          ENV: CI
          GO111MODULE: "on"
      - image: influxdb:latest
        environment:
          INFLUXD_HTTP_BIND_ADDRESS: :9999
      - image: influxdb:latest
        name: influxdb_v2_onboarding
        environment:
          INFLUXD_HTTP_BIND_ADDRESS: :9999
    environment:
      INFLUXDB_2_ONBOARDING_IP: influxdb_v2_onboarding
      INFLUXDB_2_ONBOARDING_PORT: 9999
    steps:
      - checkout
      - influxdb-onboarding
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
            mkdir -p /tmp/test-results
      - run:
          command: |
            gotestsum --junitfile /tmp/test-results/unit-tests.xml -- -race -tags=e2e -coverprofile=coverage.txt -covermode=atomic ./...
            bash <(curl -s https://codecov.io/bash)
            go tool cover -html=coverage.txt -o /tmp/artifacts/coverage.html
      - store_artifacts:
          path: /tmp/artifacts
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - tests:
          requires:
            - build